export { default as MainLayout } from './layout/MainLayout'
export { default as SearchBar } from './search-bar/SearchBar'
export { default as Loader } from './loader/Loader'
export { default as Navigation } from './navigation/Navigation'
export { default as MovieCast } from './movie-cast/MovieCast'
export { default as MovieList } from './movie-list/MovieList'
export { default as MovieReviews } from './movie-reviews/MovieReviews'
